CREATE TABLE CLIENTES (
    IdCliente       NUMBER PRIMARY KEY,
    nombre           VARCHAR2(100 BYTE) NOT NULL,
    email            VARCHAR2(100 BYTE) UNIQUE NOT NULL,
    telefo         VARCHAR2(20 BYTE),
    fecha_registro   DATE DEFAULT SYSDATE,
    activo           CHAR(1 BYTE) DEFAULT 'S' CHECK (activo IN ('S', 'N'))
);

CREATE SEQUENCE CLIENTE_ID_DL
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER ClienteID
BEFORE INSERT ON CLIENTES
FOR EACH ROW
WHEN (NEW.IdCliente IS NULL)
BEGIN
    SELECT IdCliente.NEXTVAL
    INTO   :NEW.IdCliente
    FROM   DUAL;
END;
/

CREATE TABLE PRODUCTOS (
    IdProducto     NUMBER PRIMARY KEY,
    nombre          VARCHAR2(200 BYTE) NOT NULL,
    descripcion     VARCHAR2(200 BYTE),
    precio          NUMBER(10,2) NOT NULL,
    stock           NUMBER DEFAULT 0,
    categoria       VARCHAR2(20 BYTE),
    fecha_creacion  DATE DEFAULT SYSDATE
);

CREATE SEQUENCE PRODUCTO_ID_DL
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER PRODUCTOID
BEFORE INSERT ON PRODUCTOS
FOR EACH ROW
WHEN (NEW.IdProducto IS NULL)
BEGIN
    SELECT PRODUCTO_ID.NEXTVAL
    INTO   :NEW.IdProducto
    FROM   DUAL;
END;
/

CREATE TABLE PEDIDOS (
    IdPedido      NUMBER PRIMARY KEY,
    IdCliente     NUMBER NOT NULL,
    IdProducto    NUMBER NOT NULL,
    cantidad       NUMBER NOT NULL,
    fecha_pedido   DATE DEFAULT SYSDATE,
    estado         VARCHAR2(20 BYTE) DEFAULT 'PENDIENTE',
    total         NUMBER(10,2),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (IdCliente)
        REFERENCES CLIENTES (IdCliente),
    CONSTRAINT FK_PEDIDO_PRODUCTO FOREIGN KEY (IdProducto)
        REFERENCES PRODUCTOS (IdProducto)
);


CREATE SEQUENCE PEDIDO_ID_dL
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER PEDIDOID
BEFORE INSERT ON PEDIDOS
FOR EACH ROW
WHEN (NEW.IdPedido IS NULL)
BEGIN
    SELECT PEDIDO_ID.NEXTVAL
    INTO   :NEW.IdPedido
    FROM   DUAL;
END;
/

CREATE OR REPLACE TRIGGER CALCULAR_TOTAL
BEFORE INSERT OR UPDATE ON PEDIDOS
FOR EACH ROW
DECLARE
    v_precio PRODUCTOS.PRECIO%TYPE;
BEGIN
   
    SELECT PRECIO INTO v_precio
    FROM PRODUCTOS
    WHERE IdProducto = :NEW.IdProducto;

    :NEW.TOTAL := v_precio * :NEW.CANTIDAD;
END;
/

CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_STOCK
AFTER INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
    UPDATE PRODUCTOS
    SET STOCK = STOCK - :NEW.CANTIDAD
    WHERE IdProducto = :NEW.IdProducto;
END;
/

COMMIT;


